run:
  timeout: 5m
  skip-dirs:
    - vendor
    - generated

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
  ineffassign:
    check-blank: true
  misspell:
    locale: US
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/tian841224/stock-bot

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - linters:
        - gocritic
      text: "ifElseChain|assignOp|commentFormatting"
    - linters:
        - stylecheck
      text: "ST1003.*package names"
      path: "internal/service/stock_sync"
  max-issues-per-linter: 0
  max-same-issues: 0
